zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: null
  exclude_path: null

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: ${oc.env:SMTP_SERVER}
  smtp_port: ${oc.env:SMTP_PORT}
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  generation_kwargs:
    max_tokens: 16384
    model: gpt-4o-mini
  language: English

reranker:
  local:
    model: jinaai/jina-embeddings-v5-text-nano
    encode_kwargs:
      task: retrieval
      prompt_name: document
  api:
    key: ${oc.env:EMBEDDING_API_KEY}
    base_url: ${oc.env:EMBEDDING_API_BASE}
    model: null
    batch_size: null

executor:
  debug: false
  send_empty: false
  max_paper_num: 10
  source: null
  reranker: local
